### ISSUE TITLE
Unusual DNF configuration in default install

### ISSUE THREAD

**Issue by jhasse** [WhitewaterFoundry/Pengwin-Fedora-Remix#6]
After installing from the Microsoft Store I've noticed that DNF has some unusual settings set in `/etc/dnf/dnf.conf`:

```
metadata_expires=0
```

and

```
assumeyes=1
```

This causes DNF to always check the repositories for updates on every call and install packages without asking the user first. As this isn't the case on a normal Fedora install, I think it would be a good idea to remove those two settings.

**Comment by grufwub** [comment]
PR here: #17

**Comment by jhasse** [comment]
Thanks :)
